//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public string dob { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string mobile { get; set; }
        public bool isActive { get; set; }
        public int rating { get; set; }
        public string userType { get; set; }
    }
}
